services:

  postgres:
    image: postgres:16
    container_name: JobFinder-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./Backend/JobFinderBackend
      dockerfile: Dockerfile
    container_name: JobFinder-back-end
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SUPPORT_EMAIL: ${SUPPORT_EMAIL}
      SUPPORT_PASSWORD: ${SUPPORT_PASSWORD}
      CLOUD_NAME: ${CLOUD_NAME}
      CLOUD_API_KEY: ${CLOUD_API_KEY}
      CLOUD_API_SECRET: ${CLOUD_API_SECRET}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GEMINI_API_URL: ${GEMINI_API_URL}
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./Frontend/JobFinderFrontend
      dockerfile: Dockerfile
    container_name: JobFinder-front-end
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
